dist: xenial
language: python
matrix:
  include:
    - python: 2.6
      dist: trusty
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.8-dev

services:
  - docker

install:
  - pip install tox tox-travis

script: true
